version: '3.8'

services:
  generator-service:
    build: ./generator_service
    container_name: generator-service
    ports:
      - "5000:5000"

  invoker-service:
    build: ./invoker_service
    container_name: invoker-service
    ports:
      - "5001:5001"
    env_file:
      - ./invoker_service/.env
